language: java
script: "mvn deploy --settings project-resources/ci-settings.xml"

branches:
  only:
    - master
    - smartparam-1.1.0

env:
  global:
    - secure: "f8ZO3bh7xLJtq1rPUAWJ3a1/gjj3YObohUDUOXvRkWdK6f8OKJMzokDrxcBeP0f3tSB7CdvrOl2FO4rdd2UcV4cS5noXGkmjwFW5I8X4FhevyUGzbEaz6GFM0r3UwzWzOBNTotZ8lM4SwpabAkNTvppLUE1/UDTzWVrsO/BWGF8=" 
