sudo: false

language: java

install: ./gradlew assemble
script:
  - ./gradlew check
  - ./gradlew uploadArchives -PnexusUsername=smartparam -PnexusPassword=$NEXUS_PASSWORD

jdk:
  - openjdk8

branches:
  only:
    - master

env:
  global:
    - secure: "f8ZO3bh7xLJtq1rPUAWJ3a1/gjj3YObohUDUOXvRkWdK6f8OKJMzokDrxcBeP0f3tSB7CdvrOl2FO4rdd2UcV4cS5noXGkmjwFW5I8X4FhevyUGzbEaz6GFM0r3UwzWzOBNTotZ8lM4SwpabAkNTvppLUE1/UDTzWVrsO/BWGF8=" 
